INSERT INTO `districts` (`name`, `shortname`, `base_path`) VALUES
('Adel SD 21', 'AdelSD21', ''),
('Adrian SD 61', 'AdrianSD61', ''),
('Alsea SD 7J', 'AlseaSD7J', ''),
('Amity SD 4J', 'AmitySD4J', ''),
('Annex SD 29', 'AnnexSD29', ''),
('Arlington SD 3', 'ArlingtonSD3', ''),
('Arock SD 81', 'ArockSD81', ''),
('Ashland SD 5', 'AshlandSD5', ''),
('Ashwood SD 8', 'AshwoodSD8', ''),
('Astoria SD 1', 'AstoriaSD1', ''),
('Athena-Weston SD 29RJ', 'Athena-WestonSD29RJ', ''),
('Baker SD 5J', 'BakerSD5J', ''),
('Ballston Community School', 'BallstonCommunitySchool', ''),
('Bandon SD 54', 'BandonSD54', ''),
('Banks SD 13', 'BanksSD13', ''),
('Beaverton SD 48J', 'BeavertonSD48J', ''),
('Bend--LaPine Administrative SD 1', 'Bend--LaPineAdministrativeSD1', ''),
('Bethel SD 52', 'BethelSD52', ''),
('Blachly SD 90', 'BlachlySD90', ''),
('Black Butte SD 41', 'BlackButteSD41', ''),
('Brookings-Harbor SD 17C', 'Brookings-HarborSD17C', ''),
('Burnt River SD 30J', 'BurntRiverSD30J', ''),
('Butte Falls SD 91', 'ButteFallsSD91', ''),
('Camas Valley SD 21J', 'CamasValleySD21J', ''),
('Canby SD 86', 'CanbySD86', ''),
('Cascade SD 5', 'CascadeSD5', ''),
('Centennial SD 28J', 'CentennialSD28J', ''),
('Central Curry SD 1', 'CentralCurrySD1', ''),
('Central Linn SD 552', 'CentralLinnSD552', ''),
('Central Point SD 6', 'CentralPointSD6', ''),
('Central SD 13J', 'CentralSD13J', ''),
('Clatskanie SD 6J', 'ClatskanieSD6J', ''),
('Colton SD 53', 'ColtonSD53', ''),
('Condon SD 25J', 'CondonSD25J', ''),
('Coos Bay SD 9', 'CoosBaySD9', ''),
('Coquille SD 8', 'CoquilleSD8', ''),
('Corbett SD 39', 'CorbettSD39', ''),
('Corvallis SD 509J', 'CorvallisSD509J', ''),
('Cove SD 15', 'CoveSD15', ''),
('Creswell SD 40', 'CreswellSD40', ''),
('Crook County SD', 'CrookCountySD', ''),
('Crow-Applegate-Lorane SD 66', 'Crow-Applegate-LoraneSD66', ''),
('Culver SD 4', 'CulverSD4', ''),
('Dallas SD 2', 'DallasSD2', ''),
('David Douglas SD 40', 'DavidDouglasSD40', ''),
('Dayton SD 8', 'DaytonSD8', ''),
('Dayville SD 16J', 'DayvilleSD16J', ''),
('Diamond SD 7', 'DiamondSD7', ''),
('Double O SD 28', 'DoubleOSD28', ''),
('Douglas County SD 15', 'DouglasCountySD15', ''),
('Douglas County SD 4', 'DouglasCountySD4', ''),
('Drewsey SD 13', 'DrewseySD13', ''),
('Dufur SD 29', 'DufurSD29', ''),
('Eagle Point SD 9', 'EaglePointSD9', ''),
('Echo SD 5', 'EchoSD5', ''),
('Elgin SD 23', 'ElginSD23', ''),
('Elkton SD 34', 'ElktonSD34', ''),
('Enterprise SD 21', 'EnterpriseSD21', ''),
('Estacada SD 108', 'EstacadaSD108', ''),
('Eugene SD 4J', 'EugeneSD4J', ''),
('Falls City SD 57', 'FallsCitySD57', ''),
('Fern Ridge SD 28J', 'FernRidgeSD28J', ''),
('Forest Grove SD 15', 'ForestGroveSD15', ''),
('Fossil SD 21J', 'FossilSD21J', ''),
('Frenchglen SD 16', 'FrenchglenSD16', ''),
('Gaston SD 511J', 'GastonSD511J', ''),
('Gervais SD 1', 'GervaisSD1', ''),
('Gladstone SD 115', 'GladstoneSD115', ''),
('Glendale SD 77', 'GlendaleSD77', ''),
('Glide SD 12', 'GlideSD12', ''),
('Grants Pass SD 7', 'GrantsPassSD7', ''),
('Greater Albany Public SD 8J', 'GreaterAlbanyPublicSD8J', ''),
('Gresham-Barlow SD 10J', 'Gresham-BarlowSD10J', ''),
('Harney County SD 3', 'HarneyCountySD3', ''),
('Harney County SD 4', 'HarneyCountySD4', ''),
('Harney County Union High SD 1J', 'HarneyCountyUnionHighSD1J', ''),
('Harper SD 66', 'HarperSD66', ''),
('Harrisburg SD 7J', 'HarrisburgSD7J', ''),
('Helix SD 1', 'HelixSD1', ''),
('Hermiston SD 8', 'HermistonSD8', ''),
('Hillsboro SD 1J', 'HillsboroSD1J', ''),
('Hood River County SD', 'HoodRiverCountySD', ''),
('Huntington SD 16J', 'HuntingtonSD16J', ''),
('Imbler SD 11', 'ImblerSD11', ''),
('Ione SD R2', 'IoneSDR2', ''),
('Jefferson County SD 509J', 'JeffersonCountySD509J', ''),
('Jefferson SD 14J', 'JeffersonSD14J', ''),
('Jewell SD 8', 'JewellSD8', ''),
('John Day SD 3', 'JohnDaySD3', ''),
('Jordan Valley SD 3', 'JordanValleySD3', ''),
('Joseph SD 6', 'JosephSD6', ''),
('Junction City SD 69', 'JunctionCitySD69', ''),
('Juntura SD 12', 'JunturaSD12', ''),
('Klamath County SD', 'KlamathCountySD', ''),
('Klamath Falls City Schools', 'KlamathFallsCitySchools', ''),
('Knappa SD 4', 'KnappaSD4', ''),
('La Grande SD 1', 'LaGrandeSD1', ''),
('Lake County SD 7', 'LakeCountySD7', ''),
('Lake Oswego SD 7J', 'LakeOswegoSD7J', ''),
('Lebanon Community SD 9', 'LebanonCommunitySD9', ''),
('Lincoln County SD', 'LincolnCountySD', ''),
('Long Creek SD 17', 'LongCreekSD17', ''),
('Lowell SD 71', 'LowellSD71', ''),
('Mapleton SD 32', 'MapletonSD32', ''),
('Marcola SD 79J', 'MarcolaSD79J', ''),
('McKenzie SD 68', 'McKenzieSD68', ''),
('McMinnville SD 40', 'McMinnvilleSD40', ''),
('Medford SD 549C', 'MedfordSD549C', ''),
('Milton-Freewater Unified SD 7', 'Milton-FreewaterUnifiedSD7', ''),
('Mitchell SD 55', 'MitchellSD55', ''),
('Molalla River SD 35', 'MolallaRiverSD35', ''),
('Monroe SD 1J', 'MonroeSD1J', ''),
('Monument SD 8', 'MonumentSD8', ''),
('Morrow SD 1', 'MorrowSD1', ''),
('Mt Angel SD 91', 'MtAngelSD91', ''),
('Myrtle Point SD 41', 'MyrtlePointSD41', ''),
('Neah-Kah-Nie SD 56', 'Neah-Kah-NieSD56', ''),
('Nestucca Valley SD 101J', 'NestuccaValleySD101J', ''),
('Newberg SD 29J', 'NewbergSD29J', ''),
('North Bend SD 13', 'NorthBendSD13', ''),
('North Clackamas SD 12', 'NorthClackamasSD12', ''),
('North Douglas SD 22', 'NorthDouglasSD22', ''),
('North Lake SD 14', 'NorthLakeSD14', ''),
('North Marion SD 15', 'NorthMarionSD15', ''),
('North Powder SD 8J', 'NorthPowderSD8J', ''),
('North Santiam SD 29J', 'NorthSantiamSD29J', ''),
('North Wasco County SD 21', 'NorthWascoCountySD21', ''),
('Nyssa SD 26', 'NyssaSD26', ''),
('Oakland SD 1', 'OaklandSD1', ''),
('Oakridge SD 76', 'OakridgeSD76', ''),
('ODE YCEP District', 'ODEYCEPDistrict', ''),
('ODE EII', 'ODEEII', ''),
('Ontario SD 8C', 'OntarioSD8C', ''),
('Oregon City SD 62', 'OregonCitySD62', ''),
('Oregon Department of Education', 'OregonDepartmentofEducation', ''),
('Oregon Trail SD 46', 'OregonTrailSD46', ''),
('Paisley SD 11', 'PaisleySD11', ''),
('Parkrose SD 3', 'ParkroseSD3', ''),
('Pendleton SD 16', 'PendletonSD16', ''),
('Perrydale SD 21', 'PerrydaleSD21', ''),
('Philomath SD 17J', 'PhilomathSD17J', ''),
('Phoenix-Talent SD 4', 'Phoenix-TalentSD4', ''),
('Pilot Rock SD 2', 'PilotRockSD2', ''),
('Pine Creek SD 5', 'PineCreekSD5', ''),
('Pine Eagle SD 61', 'PineEagleSD61', ''),
('Pinehurst SD 94', 'PinehurstSD94', ''),
('Pleasant Hill SD 1', 'PleasantHillSD1', ''),
('Plush SD 18', 'PlushSD18', ''),
('Port Orford-Langlois SD 2CJ', 'PortOrford-LangloisSD2CJ', ''),
('Portland SD 1J', 'PortlandSD1J', ''),
('Powers SD 31', 'PowersSD31', ''),
('Prairie City SD 4', 'PrairieCitySD4', ''),
('Prospect SD 59', 'ProspectSD59', ''),
('Rainier SD 13', 'RainierSD13', ''),
('Redmond SD 2J', 'RedmondSD2J', ''),
('Reedsport SD 105', 'ReedsportSD105', ''),
('Reynolds SD 7', 'ReynoldsSD7', ''),
('Riddle SD 70', 'RiddleSD70', ''),
('Riverdale SD 51J', 'RiverdaleSD51J', ''),
('Rogue River SD 35', 'RogueRiverSD35', ''),
('Salem-Keizer SD 24J', 'Salem-KeizerSD24J', ''),
('Santiam Canyon SD 129J', 'SantiamCanyonSD129J', ''),
('Scappoose SD 1J', 'ScappooseSD1J', ''),
('Scio SD 95', 'ScioSD95', ''),
('Seaside SD 10', 'SeasideSD10', ''),
('Sheridan SD 48J', 'SheridanSD48J', ''),
('Sherman County SD', 'ShermanCountySD', ''),
('Sherwood SD 88J', 'SherwoodSD88J', ''),
('Silver Falls SD 4J', 'SilverFallsSD4J', ''),
('Sisters SD 6', 'SistersSD6', ''),
('Siuslaw SD 97J', 'SiuslawSD97J', ''),
('South Harney SD 33', 'SouthHarneySD33', ''),
('South Lane SD 45J3', 'SouthLaneSD45J3', ''),
('South Umpqua SD 19', 'SouthUmpquaSD19', ''),
('South Wasco County SD 1', 'SouthWascoCountySD1', ''),
('Spray SD 1', 'SpraySD1', ''),
('Springfield SD 19', 'SpringfieldSD19', ''),
('St Helens SD 502', 'StHelensSD502', ''),
('St Paul SD 45', 'StPaulSD45', ''),
('Stanfield SD 61', 'StanfieldSD61', ''),
('Suntex SD 10', 'SuntexSD10', ''),
('Sutherlin SD 130', 'SutherlinSD130', ''),
('Sweet Home SD 55', 'SweetHomeSD55', ''),
('Three Rivers/Josephine County SD', 'ThreeRivers/JosephineCountySD', ''),
('Tigard-Tualatin SD 23J', 'Tigard-TualatinSD23J', ''),
('Tillamook SD 9', 'TillamookSD9', ''),
('Troy SD 54', 'TroySD54', ''),
('Ukiah SD 80R', 'UkiahSD80R', ''),
('Umatilla SD 6R', 'UmatillaSD6R', ''),
('Union SD 5', 'UnionSD5', ''),
('Vale SD 84', 'ValeSD84', ''),
('Vernonia SD 47J', 'VernoniaSD47J', ''),
('Wallowa SD 12', 'WallowaSD12', ''),
('Warrenton-Hammond SD 30', 'Warrenton-HammondSD30', ''),
('West Linn-Wilsonville SD 3J', 'WestLinn-WilsonvilleSD3J', ''),
('Willamina SD 30J', 'WillaminaSD30J', ''),
('Winston-Dillard SD 116', 'Winston-DillardSD116', ''),
('Woodburn SD 103', 'WoodburnSD103', ''),
('Yamhill-Carlton SD 1', 'Yamhill-CarltonSD1', ''),
('Yoncalla SD 32', 'YoncallaSD32', ''),
('Marylhurst', 'Marylhurst', ''),
('Roseburg', 'Roseburg', ''),
('John Day', 'JohnDay', ''),
('Burns', 'Burns', ''),
('Redmond', 'Redmond', ''),
('Eugene', 'Eugene', ''),
('Albany', 'Albany', ''),
('Vale', 'Vale', ''),
('Portland', 'Portland', ''),
('Condon', 'Condon', ''),
('Hillsboro', 'Hillsboro', ''),
('The Dalles', 'TheDalles', ''),
('Enterprise', 'Enterprise', ''),
('Coos Bay (north) & Gold Beach (south)', 'CoosBay(north)&GoldBeach(south)', ''),
('Medford', 'Medford', ''),
('Pendleton', 'Pendleton', ''),
('La Grande', 'LaGrande', ''),
('Salem', 'Salem', ''),
('ORVSD', 'ORVSD', '');
